// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMT_Baitap_MVCTaiLop.Models;

#nullable disable

namespace PMT_BT_MVC_TaiLop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.DangKyLopHoc", b =>
                {
                    b.Property<int>("DangKyLopHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DangKyLopHocId"));

                    b.Property<int>("LopHocPhanId")
                        .HasColumnType("int");

                    b.Property<int>("SinhVienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ngaydk")
                        .HasColumnType("datetime2");

                    b.HasKey("DangKyLopHocId");

                    b.HasIndex("LopHocPhanId");

                    b.HasIndex("SinhVienId");

                    b.ToTable("dangKyLopHocs");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.GiaoVien", b =>
                {
                    b.Property<int>("GiaoVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GiaoVienId"));

                    b.Property<string>("tenGV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GiaoVienId");

                    b.ToTable("giaoViens");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.KhoaHoc", b =>
                {
                    b.Property<int>("KhoaHocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KhoaHocId"));

                    b.Property<string>("tenKH")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KhoaHocId");

                    b.ToTable("khoaHocs");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.LopHocPhan", b =>
                {
                    b.Property<int>("LopHocPhanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LopHocPhanId"));

                    b.Property<int>("GiaoVienId")
                        .HasColumnType("int");

                    b.Property<int>("KhoaHocId")
                        .HasColumnType("int");

                    b.Property<string>("tenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LopHocPhanId");

                    b.HasIndex("GiaoVienId");

                    b.HasIndex("KhoaHocId");

                    b.ToTable("lopHocPhans");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.SinhVien", b =>
                {
                    b.Property<int>("SinhVienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SinhVienId"));

                    b.Property<string>("tenSinhVien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SinhVienId");

                    b.ToTable("sinhViens");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.DangKyLopHoc", b =>
                {
                    b.HasOne("PMT_Baitap_MVCTaiLop.Models.LopHocPhan", "LopHocPhan")
                        .WithMany("dangKyLopHocs")
                        .HasForeignKey("LopHocPhanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMT_Baitap_MVCTaiLop.Models.SinhVien", "SinhVien")
                        .WithMany("dangKyLopHocs")
                        .HasForeignKey("SinhVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LopHocPhan");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.LopHocPhan", b =>
                {
                    b.HasOne("PMT_Baitap_MVCTaiLop.Models.GiaoVien", "GiaoVien")
                        .WithMany("lopHocPhans")
                        .HasForeignKey("GiaoVienId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PMT_Baitap_MVCTaiLop.Models.KhoaHoc", "KhoaHoc")
                        .WithMany("lopHocPhans")
                        .HasForeignKey("KhoaHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.GiaoVien", b =>
                {
                    b.Navigation("lopHocPhans");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.KhoaHoc", b =>
                {
                    b.Navigation("lopHocPhans");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.LopHocPhan", b =>
                {
                    b.Navigation("dangKyLopHocs");
                });

            modelBuilder.Entity("PMT_Baitap_MVCTaiLop.Models.SinhVien", b =>
                {
                    b.Navigation("dangKyLopHocs");
                });
#pragma warning restore 612, 618
        }
    }
}
